services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundle\RestBundle\Controller\ResourceController: ~

    App\Bundle\RestBundle\Processor\ActionProcessorBag: ~

    App\Bundle\RestBundle\Processor\ActionProcessorBagInterface: '@App\Bundle\RestBundle\Processor\ActionProcessorBag'

    App\Bundle\RestBundle\Processor\SerializerFormat: ~

    App\Bundle\RestBundle\Provider\FormatsProvider:
        arguments:
            - '%app_rest.formats%'

    App\Bundle\RestBundle\Provider\FormatsProviderInterface: '@App\Bundle\RestBundle\Provider\FormatsProvider'

    App\Bundle\RestBundle\Handler\ViewHandler: ~

    App\Bundle\RestBundle\Handler\ViewHandlerInterface:  '@App\Bundle\RestBundle\Handler\ViewHandler'
