app_rest:
    actions:
            # get_list:
            #     processor_service_id: app_rest.get_list.processor
            #     processing_groups:
            #         initialize:
            #             priority: -10
            #         resource_check:
            #             priority: -15
            #         normalize_input:
            #             priority: -20
            #         security_check:
            #             priority: -30
            #         build_query:
            #             priority: -40
            #         load_data:
            #             priority: -50
            #         data_security_check:
            #             priority: -55
            #         normalize_data:
            #             priority: -60
            #         finalize:
            #             priority: -70
            #         normalize_result:
            #             priority: -80
            view:
                processor_service_id: App\Bundle\RestBundle\Processor\View\ViewProcessor
                processing_groups:
                    initialize:
                        priority: -10
                    security:
                        priority: -15
                    finalize:
                        priority: -70
            # delete:
            #     processor_service_id: app_rest.delete.processor
            #     processing_groups:
            #         initialize:
            #             priority: -10
            #         resource_check:
            #             priority: -15
            #         normalize_input:
            #             priority: -20
            #         security_check:
            #             priority: -30
            #         load_data:
            #             priority: -40
            #         data_security_check:
            #             priority: -45
            #         delete_data:
            #             priority: -50
            #         finalize:
            #             priority: -60
            #         normalize_result:
            #             priority: -70
            # delete_list:
            #     processor_service_id: app_rest.delete_list.processor
            #     processing_groups:
            #         initialize:
            #             priority: -10
            #         resource_check:
            #             priority: -15
            #         normalize_input:
            #             priority: -20
            #         security_check:
            #             priority: -30
            #         build_query:
            #             priority: -40
            #         load_data:
            #             priority: -50
            #         data_security_check:
            #             priority: -55
            #         delete_data:
            #             priority: -60
            #         finalize:
            #             priority: -70
            #         normalize_result:
            #             priority: -80
            create:
                processor_service_id: App\Bundle\RestBundle\Processor\Create\CreateProcessor
                processing_groups:
                    initialize:
                        priority: -10
                    security:
                        priority: -15
                    deserialize:
                        priority: -20
                    validate:
                        priority: -30
                    transform:
                        priority: -40
                    save:
                        priority: -50
                    finalize:
                        priority: -60
            update:
                processor_service_id: App\Bundle\RestBundle\Processor\Update\UpdateProcessor
                processing_groups:
                    initialize:
                        priority: -10
                    security:
                        priority: -15
                    deserialize:
                        priority: -20
                    validate:
                        priority: -30
                    transform:
                        priority: -40
                    save:
                        priority: -50
                    finalize:
                        priority: -60
