app_rest:
    filters:
        string: ~
        boolean: ~
        integer:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        smallint:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        bigint:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        unsignedInteger:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        decimal:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        float:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        date:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        time:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        datetime:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        guid: ~
        text:
            # by default, only EXISTS (IS NOT NULL) and NOT EXISTS (IS NULL) operators
            # are enabled for text fields,
            # to enable other operators for a particular field the "operators" option should be
            # specified for this field in api.yml configuration file, in "filters" section
            supported_operators: ['*']
        percent:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        money:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        money_value:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        currency: ~
        duration:
            supported_operators: ['=', '!=', '<', '<=', '>', '>=', '*', '!*']
        # composite_identifier:
        #     factory: ['@app_rest.filter_factory.composite_identifier', 'createFilter']
        # association:
        #     factory: ['@app_rest.filter_factory.extended_association', 'createFilter']
        primaryField:
            class: App\Bundle\RestBundle\Filter\PrimaryFieldFilter
    filter_operators:
        eq:  '='  # equal to
        neq: '!=' # not equal to
        gt:  '>'  # greater than
        lt:  '<'  # less than
        gte: '>=' # greater than or equal to
        lte: '<=' # less than or equal to
        exists: '*' # exists (IS NOT NULL) and not exists (IS NULL), value is true = exists, value is false = not exists
        neq_or_null:     '!*' # not equal to or IS NULL
        contains:        '~'  # contains (LIKE %value%)
        not_contains:    '!~' # not contains (NOT LIKE %value%)
        starts_with:     '^'  # starts with (LIKE value%)
        not_starts_with: '!^' # not starts with (NOT LIKE value%)
        ends_with:       '$'  # ends with (LIKE %value)
        not_ends_with:   '!$' # not ends with (NOT LIKE %value)
    actions:
            index:
                processor_service_id: App\Bundle\RestBundle\Processor\Index\IndexProcessor
                processing_groups:
                    initialize:
                        priority: -10
                    security:
                        priority: - 15
                    build_query:
                        priority: -20
                    index:
                        priority: -25
                    finalize:
                        priority: -30
            view:
                processor_service_id: App\Bundle\RestBundle\Processor\View\ViewProcessor
                processing_groups:
                    initialize:
                        priority: -10
                    security:
                        priority: -15
                    finalize:
                        priority: -20
            delete:
                processor_service_id: App\Bundle\RestBundle\Processor\Delete\DeleteProcessor
                processing_groups:
                    initialize:
                        priority: -10
                    security:
                        priority: -15
                    delete:
                        priority:  -20
                    finalize:
                        priority:  -25
            bulk_delete:
                processor_service_id: App\Bundle\RestBundle\Processor\BulkDelete\BulkDeleteProcessor
                processing_groups:
                    initialize:
                        priority: -10
                    security:
                        priority: -15
                    build_query:
                        priority: -20
                    delete:
                        priority:  -25
                    finalize:
                        priority:  -30
            create:
                processor_service_id: App\Bundle\RestBundle\Processor\Create\CreateProcessor
                processing_groups:
                    initialize:
                        priority: -10
                    security:
                        priority: -15
                    deserialize:
                        priority: -20
                    validate:
                        priority: -30
                    transform:
                        priority: -40
                    save:
                        priority: -50
                    finalize:
                        priority: -60
            update:
                processor_service_id: App\Bundle\RestBundle\Processor\Update\UpdateProcessor
                processing_groups:
                    initialize:
                        priority: -10
                    security:
                        priority: -15
                    deserialize:
                        priority: -20
                    validate:
                        priority: -30
                    transform:
                        priority: -40
                    save:
                        priority: -50
                    finalize:
                        priority: -60
